package Modelos;
// Generated 03-dic-2022 18:40:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Matriculas generated by hbm2java
 */
public class Matriculas  implements java.io.Serializable {

    //Atributos de la clase
    private MatriculasId id;
    private Alumnos alumnos;
    private Cursos cursos;
    private short nnotamedia;
    private Set exameneses = new HashSet(0);

    
    //Constructores
    public Matriculas() {
    }
    public Matriculas(MatriculasId id, Alumnos alumnos, Cursos cursos, short nnotamedia) {
        this.id = id;
        this.alumnos = alumnos;
        this.cursos = cursos;
        this.nnotamedia = nnotamedia;
    }
    public Matriculas(MatriculasId id, Alumnos alumnos, Cursos cursos, short nnotamedia, Set exameneses) {
       this.id = id;
       this.alumnos = alumnos;
       this.cursos = cursos;
       this.nnotamedia = nnotamedia;
       this.exameneses = exameneses;
    }
   
    //Getters y setters
    public MatriculasId getId() {
        return this.id;
    }    
    public void setId(MatriculasId id) {
        this.id = id;
    }
    
    public Alumnos getAlumnos() {
        return this.alumnos;
    }    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    
    public Cursos getCursos() {
        return this.cursos;
    }    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    
    public short getNnotamedia() {
        return this.nnotamedia;
    }    
    public void setNnotamedia(short nnotamedia) {
        this.nnotamedia = nnotamedia;
    }
    
    public Set getExameneses() {
        return this.exameneses;
    }    
    public void setExameneses(Set exameneses) {
        this.exameneses = exameneses;
    }
    
    //metodo para calcula la nota media
    public BigDecimal calcularNotaMedia(){
        ArrayList<Examenes> examenes = new ArrayList<Examenes>(this.exameneses);
        double notaTotal = 0;
        double notaMedia = 0;
        for(int i = 0; i < examenes.size(); i++){
            BigDecimal nota = examenes.get(i).getNnotaexam();
            notaTotal = notaTotal + nota.doubleValue();
        }
        notaMedia = notaTotal / examenes.size();
        BigDecimal notaFinal = new BigDecimal(notaMedia);
        return notaFinal;
    }
}


